#!/usr/bin/perl
#
# @File pFuncProteins.pl
# @Author Iva Veseli, Illinois Institute of Technology
# @Created Jul 23, 2015 10:39:01 AM
#
# pFuncProteins ~= "Putative Function Proteins"
# Takes .tsv files generated by Interproscan5 and for each one,
  # finds and counts how many distinct proteins have at least one GO (gene ontology)
  # generates a file listing all of those distinct proteins (by locus tag)
# Also generates a summary file with the count of pFunc proteins in each .tsv

# Input file(s): *.ipr.tsv file(s)
# Output files: A summary pFuncCounts.txt file and a *.pFuncs.txt file for each .ipr.tsv file

use strict;
use warnings;

my $usage = "perl pFuncProteins.pl *.ipr.tsv\n";
die $usage unless @ARGV;

open COUNTS, ">pFuncCounts.txt" or die "Cannot open pFuncCounts.txt: $!\n";
print COUNTS "Filename\t\tNumber of proteins with at least one GO\n\n";

while (my $file = shift @ARGV)
{
    open IN, "$file" or die "Cannot open $file: $!\n";
    my $genome = $file;
    $genome =~ s/.ipr.tsv//;
    open OUT, ">$genome.pFuncs.txt" or die "Cannot open $genome.pFuncs.txt: $!\n";

    my $count = 0;
    my %proteins;

    while (<IN>)
    {
        chomp(my $line = $_);
        my @splitLine = split /\t/, $line; #.tsv files are tab-delimited, first field is locus tag
        my $locus = $splitLine[0];
        unless (exists $proteins{$locus}) #if this protein isn't already in the hash
        {
            $proteins{$locus} = 1; #arbitrary value
            $count++; #count this protein
            print OUT "$locus\n"; #print locus to list of pFuncs for this genome
        }
    }
    print COUNTS "$file\t$count\n";
}
